# Generated by Django 4.2.4 on 2023-08-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sport')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sports',
                'verbose_name_plural': 'Users Sports',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_choice', models.CharField(choices=[('oth', 'Autre')], max_length=3)),
                ('raisons', models.CharField(max_length=128)),
                ('attente_choice', models.CharField(choices=[('oth', 'Autre')], max_length=3)),
                ('attentes', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('ville', models.CharField(max_length=128)),
                ('frequence_entrainement', models.CharField(choices=[('tlj', 'Très élevée (Tous les jours)'), ('elv', 'Élevée (4 à 5 fois par semaine)'), ('nrm', 'Normale (2 à 3 fois par semaine)'), ('bas', 'Basse (1 fois par semaine)'), ('tet', 'Très basse (De temps en temps)'), ('non', 'Non renseignée'), ('var', 'Variable')], default='non', max_length=3)),
                ('objectif_court_terme', models.CharField(blank=True, max_length=128)),
                ('objectif_long_terme', models.CharField(blank=True, max_length=128)),
                ('plus_gros_defi_releve', models.CharField(blank=True, max_length=128)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
            },
        ),
    ]
