# Generated by Django 4.2.4 on 2023-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attentes',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='raisons',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
