# Generated by Django 4.2.4 on 2023-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='abrev',
            field=models.CharField(default='oth', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='icon_url',
            field=models.URLField(default='oth', max_length=128),
            preserve_default=False,
        ),
    ]
