# Generated by Django 4.2.4 on 2023-09-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user2_id',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='usersports',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='usersports',
            old_name='user_id',
            new_name='user',
        ),
    ]
