# Generated by Django 4.2.4 on 2023-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_sport_abrev_sport_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='icon_url',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
