# Generated by Django 4.2.4 on 2023-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_sport_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='frequence_entrainement',
            field=models.CharField(default='Non renseignée', max_length=128),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attente_choice',
            field=models.CharField(max_length=1228),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='raison_choice',
            field=models.CharField(max_length=128),
        ),
    ]
