# Generated by Django 4.2.4 on 2023-09-09 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_api', '0004_friendrequests_appuser_friends_alter_appuser_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequests',
            new_name='FriendRequest',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
