# Generated by Django 4.2.4 on 2023-08-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_appuser_frequence_entrainement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='frequence_entrainement',
            field=models.CharField(choices=[('tlj', 'Très élevée (Tous les jours)'), ('elv', 'Élevée (4 à 5 fois par semaine)'), ('nrm', 'Normale (2 à 3 fois par semaine)'), ('bas', 'Basse (1 fois par semaine)'), ('tet', 'Très basse (De temps en temps)'), ('non', 'Non renseignée'), ('var', 'Variable')], default='non', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attente_choice',
            field=models.CharField(max_length=128),
        ),
    ]
