# Generated by Django 4.2.4 on 2023-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_appuser_frequence_entrainement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='attente_choice',
            field=models.CharField(choices=[('ren', 'Faire des rencontres'), ('mot', 'Trouver de la motivation'), ('oth', 'Autre')], default='oth', max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='raison_choice',
            field=models.CharField(choices=[('ami', "Un ami m'en a parlé"), ('pub', 'Une publicité'), ('app', "Depuis l'AppStore"), ('oth', 'Autre')], default='oth', max_length=3),
        ),
    ]
