# Generated by Django 4.2.5 on 2023-09-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_rename_friendrequests_friendrequest_and_more'),
        ('user_api', '0006_alter_feedback_attente_choice_and_more'),
    ]

    operations = [
    ]
