# Generated by Django 4.2.5 on 2023-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_merge_20230922_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='sports', to='user_api.sport'),
        ),
        migrations.DeleteModel(
            name='UserSports',
        ),
    ]
